workflows:
  ios-ipa-build:
    name: 🎉 iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.pub-cache
        - ios/Pods

    scripts:
      - name: Flutter pub get
        script: |
          set -e
          flutter pub get

      - name: Change CODE_SIGN_STYLE to Manual
        script: |
          set -e
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Set iOS deployment target
        script: |
          set -e
          cd ios
          if ! grep -q "platform :ios, '16.0'" Podfile; then
            echo "platform :ios, '16.0'" | cat - Podfile > temp && mv temp Podfile
          fi
          cd ..

      - name: Clean and update CocoaPods
        script: |
          set -e
          rm -f ios/Podfile.lock
          cd ios
          pod repo update
          pod deintegrate
          pod install
          cd ..

      - name: Disable Code Signing
        script: |
          set -e
          sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = .*/CODE_SIGN_IDENTITY = "";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = .*/PROVISIONING_PROFILE_SPECIFIER = "";/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build iOS (no signing)
        script: |
          set -e
          flutter build ios --release --no-codesign --no-tree-shake-icons

      - name: Create IPA
        script: |
          set -e
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload

    artifacts:
      - build/ios/iphoneos/FlutterIpaExport.ipa