name: flosy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  font_awesome_flutter: ^11.0.0
  easy_localization: ^3.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.1.2
  http: ^1.6.0
  pie_chart: ^5.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  sqflite_common_ffi_web: any
  local_auth: ^2.3.0 
  image_picker: ^1.2.1
  pdf: ^3.10.4
  printing: ^5.11.0
  permission_handler: ^11.0.1
  tflite_flutter: ^0.12.1
  device_info_plus: ^10.1.0
  flutter_secure_storage: ^10.0.0
  connectivity_plus: ^7.0.0
  animate_do: ^4.2.0
  audioplayers: ^5.2.1
  audio_waveforms: ^1.0.4
  flutter_sound: ^9.30.0
  equatable: ^2.0.8
  flutter_dotenv: ^6.0.0
  google_sign_in: ^7.2.0
  # audio_session: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/models/
    - assets/fonts/
    - api.env
